---
openapi: 3.0.0
info:
   version: 1.3.0
   title: llmchat open api specification
   description: rolepermission API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8013
     description: rolepermission
tags:
- name: rolepermission
- name: role
- name: organization
paths:
   "/rolepermission/{id}":
      delete:
         tags:
         -  rolepermission
         description: GpDelete
         parameters:
         -  in: "path"
            description: GpDelete
            name: id
            required: true
            schema:
               type: "string"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      get:
         tags:
         -  rolepermission
         description: GpGetEntityById
         parameters:
         -  in: "path"
            description: GpGetEntityById
            name: id
            required: true
            schema:
               type: "string"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/rolepermission/get/search":
      get:
         tags:
         -  rolepermission
         description: GpSearch
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/rolepermission/get/update":
      put:
         tags:
         -  rolepermission
         description: GpSearchForUpdate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/rolepermission"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/rolepermission":
      put:
         tags:
         -  rolepermission
         description: GpUpdate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/rolepermission"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      get:
         tags:
         -  rolepermission
         description: GpGetAllValues
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      post:
         tags:
         -  rolepermission
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/rolepermission"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/rolepermission/userid/created_by":
      get:
         tags:
         -  rolepermission
         description: GpGetNounCreatedBy
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      rolepermission:
         type: object
         properties:
            role_ids:
               type: "string"
               description: Description
            data_permission:
               type: "string"
               description: Description
            definition:
               type: "string"
               description: Description
            roles:
               type: "string"
               description: Description
      role:
         type: object
         properties:
            org_ids:
               type: "string"
               description: Description
            roles:
               type: "string"
               description: Description
      organization:
         type: object
         properties:
            realm_name:
               type: "string"
               description: Description